[#ftl]
[@b.head/]
[@b.toolbar title="预警详细信息"/]
[@b.grid items=warnings var="warning"]
    [@b.row]
        [@b.col title="序号"  width="5%"]${warning_index+1}[/@]
        [@b.col width="10%" property="std.user.code" title="学号"/]
        [@b.col width="8%" property="std.user.name" title="姓名"/]
        [@b.col width="15%" property="std.state.squad.name" title="班级"/]
        [@b.col width="7%" property="std.state.grade" title="年级"/]
        [@b.col width="15%" property="std.state.department.name" title="院系"/]
        [@b.col width="10%" property="warningType.name" title="预警类别"/]
        [@b.col width="30%" property="detail" title="情况说明" style="white-space:pre"]
            [@b.a href="grade-warning!courseGradeInfo?gradeWarningIds="+warning.id]${warning.detail!}[/@]
        [/@]
    [/@]
[/@]
[@b.foot/]
